### ISSUE TITLE
External storage MD files not opened in editor?

### ISSUE THREAD

**Issue by stampf** [icewind1991/owncloud-markdown#12]
I have an file.md inside an external storage (Dropbox), but when I click it, it is downloaded, not opened in the editor. 

MD files in normlal ownCloud are edited properly, as well as .txt files inside Dropbox.

I have ownCloud 8.0.2 and latest version of owncloud-markdown as well.

**Comment by icewind1991** [comment]
With the dropbox external storage the mimetype of a file is determined by dropbox, if dropbox does not return the expected mimetype for markdown files the editor wont be able to recognize the files as markdown.

Feel free to open an issue in core about handling mimetypes that are unsupported by an external storage backend.
