### ISSUE TITLE
Missing Preview in OC 8.1.1

### ISSUE THREAD

**Issue by joede** [icewind1991/owncloud-markdown#16]
I've been using the *owncloud-markdown* with OC 7 for a longer time now, and it was running without problems. Yesterday, I've upgraded two installations from OC7 to OC 8.1.1. After this and after a pull of the recent version of *owncloud-markdown* (I think my previous version was 1/2 year old), the preview isn't visible anymore. Is it possible to toggle the preview on / off? I can't seen settings like this.

**Comment by icewind1991** [comment]
oc-markdown only work with the 2.0 version for the texteditor (will ship with oc8.2), you'll need https://github.com/icewind1991/owncloud-markdown/tree/a7f048bcfbc086915a4e6d8508cd6a9bb3f87cea for 8.1

**Comment by joede** [comment]
Thanks for the fast answer. It would be a good idea to tag the lastest possible release (for example last-OC8.1). ;-)

**Comment by joede** [comment]
OK, the older commit is working. ;-)
